---
name: cmpsc-301-Fall-2021-lab4
break: true
indent: 4
---

# --> check the technical writing
writing/discussion.md:
    ConfirmFileExists
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact

src/vaccines.r:
    ConfirmFileExists
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact



# --> check the number of commits beyond a threshold
CountCommits --count 3
